### PR TITLE
fix #21 update to use newer gradle APIs

### LINKED ISSUE #21: Update to new gradle configuration names
The plugin uses deprecated gradle APIs and concepts, in particular when it comes to configuration names (eg compile vs implementation, etc).
This prevents projects that use the jcstress-gradle-plugin from using the correct names as well, as gradle provides compatibility in one direction, but not the other.

### PR DESCRIPTION
**Pull request by ericbottard**

### CODE REVIEW

**Comment by jerzykrlk** [comment]
Hey Eric, thank you so much for the pull request. 

I just realized that Travis wouldn't build the JDK 8 project anymore, so I had to update it to openjdk11. Would you mind rebasing to the newest master, to build it cleanly? 

Thank you!

**Comment by ericbottard** [comment]
Fixed the ITs that I completely missed in the first pass.

Happy to discuss with you regarding the changes, as I'm not sure I got them all 100% correct (despite tests now passing). There may be some confusion wrt the role of the jcstress configuration vs. the sourceset.

**Comment by jerzykrlk** [comment]
Hello again.

Thank you for fixing the tests. I saw that they were failing, but unfortunately I had little time to look into details.

I'm by no means a Gradle or Jcstress expert - but the test coverage is pretty okay, so I think it should be okay. I will try to find some time tomorrow to locally run some old jcstress suites - either mine, or some from the Internet. I'll make sure that they pass with the new plugin version, and then we're ready to go.

Thank you again for the contribution!
Jerzy

**Comment by jerzykrlk** [comment]
Hello Eric.

I've checked, approved and merged. Is there something else you'd like to add here before I release a new version?

Thanks,
Jerzy

**Pull request merged**
